[project]
name = "my-fastapi-app"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "dengke", email = "dengke@engine3d.com" }
]
requires-python = ">=3.14"
dependencies = [
    "fastapi[standard]>=0.141.1",
    "psycopg[binary]>=3.3.5",
    "pwdlib[argon2]>=0.3.1",
    "pyjwt>=2.13.0",
    "python-dotenv>=1.2.3",
    "python-multipart>=0.0.32",
    "sqlmodel>=0.0.42",
]

[project.scripts]
my-fastapi-app = "my_fastapi_app:main"

[build-system]
requires = ["uv_build>=0.12.10,<0.13.0"]
build-backend = "uv_build"
